# Generated by Django 4.1.7 on 2023-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(max_length=20)),
                ('amount_invested', models.PositiveIntegerField()),
                ('invested_on', models.DateField(auto_now=True)),
                ('investment_rate', models.FloatField()),
            ],
        ),
    ]
