# Generated by Django 4.1.7 on 2023-03-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registration_phone_number_transaction_leaver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='amount_invested',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='invested_on',
        ),
        migrations.AddField(
            model_name='investment',
            name='principal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CTB', 'Contribution'), ('RPT', 'Repayment'), ('INV', 'Investment')], max_length=3),
        ),
    ]
